version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment: 
      MYSQL_DATABASE: "lojavirtual"
      MYSQL_ROOT_PASSWORD: "root"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db_data:/usr/data
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    restart: unless-stopped
    volumes: 
      - ./src:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-avaliable/000-default.conf
      - ./apache_log:/var/log/apache2
    ports:
      - 8000:443
    depends_on: 
      - db
    links:
      - db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  db_data:
  src: